### ISSUE TITLE
Convert DT-FKDFT13 into devenv

### ISSUE THREAD

**Issue by Reinitialized** [Reinitialized/reinitialized.net#5]
# Overview
Convert DT-FKDFT13 into new devenv

# Tasks
- [ ] Move DT-11HB9N2 into office
- [ ] Migrate contents of DT-FKDFT13 onto DT-11HB9N2
- [ ] Install CentOS Stream onto DT-FKDFT13
  - [ ] Setup according to Server Configuration Procedure
  - [ ] Install Docker
  - [ ] Install Sysbox
  - [ ] Setup develop user
  - [ ] Install code-server
